services:
  app:
    environment:
      NODE_ENV: development
      THUNDERSTRUX_RUNTIME_CONTAINER: "false"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: pnpm dev

  db:
    ports:
      - "5433:5432"

volumes:
  node_modules:
